(()=>{var e={};e.id=507,e.ids=[507,888,660],e.modules={4297:(e,t,r)=>{"use strict";r.d(t,{Z:()=>n});var s=r(6689),a={xmlns:"http://www.w3.org/2000/svg",width:24,height:24,viewBox:"0 0 24 24",fill:"none",stroke:"currentColor",strokeWidth:2,strokeLinecap:"round",strokeLinejoin:"round"};/**
 * @license lucide-react v0.340.0 - ISC
 *
 * This source code is licensed under the ISC license.
 * See the LICENSE file in the root directory of this source tree.
 */let i=e=>e.replace(/([a-z0-9])([A-Z])/g,"$1-$2").toLowerCase().trim(),n=(e,t)=>{let r=(0,s.forwardRef)(({color:r="currentColor",size:n=24,strokeWidth:l=2,absoluteStrokeWidth:u,className:o="",children:c,...d},p)=>(0,s.createElement)("svg",{ref:p,...a,width:n,height:n,stroke:r,strokeWidth:u?24*Number(l)/Number(n):l,className:["lucide",`lucide-${i(e)}`,o].join(" "),...d},[...t.map(([e,t])=>(0,s.createElement)(e,t)),...Array.isArray(c)?c:[c]]));return r.displayName=`${e}`,r}},3756:(e,t,r)=>{"use strict";r.d(t,{Z:()=>s});/**
 * @license lucide-react v0.340.0 - ISC
 *
 * This source code is licensed under the ISC license.
 * See the LICENSE file in the root directory of this source tree.
 */let s=(0,r(4297).Z)("CheckCircle",[["path",{d:"M22 11.08V12a10 10 0 1 1-5.93-9.14",key:"g774vq"}],["path",{d:"m9 11 3 3L22 4",key:"1pflzl"}]])},1323:(e,t)=>{"use strict";Object.defineProperty(t,"l",{enumerable:!0,get:function(){return function e(t,r){return r in t?t[r]:"then"in t&&"function"==typeof t.then?t.then(t=>e(t,r)):"function"==typeof t&&"default"===r?t:void 0}}})},9472:(e,t,r)=>{"use strict";r.r(t),r.d(t,{config:()=>P,default:()=>o,getServerSideProps:()=>p,getStaticPaths:()=>d,getStaticProps:()=>c,reportWebVitals:()=>m,routeModule:()=>x,unstable_getServerProps:()=>S,unstable_getServerSideProps:()=>b,unstable_getStaticParams:()=>f,unstable_getStaticPaths:()=>h,unstable_getStaticProps:()=>g});var s=r(7093),a=r(5244),i=r(1323),n=r(29),l=r(5143),u=r(4113);let o=(0,i.l)(u,"default"),c=(0,i.l)(u,"getStaticProps"),d=(0,i.l)(u,"getStaticPaths"),p=(0,i.l)(u,"getServerSideProps"),P=(0,i.l)(u,"config"),m=(0,i.l)(u,"reportWebVitals"),g=(0,i.l)(u,"unstable_getStaticProps"),h=(0,i.l)(u,"unstable_getStaticPaths"),f=(0,i.l)(u,"unstable_getStaticParams"),S=(0,i.l)(u,"unstable_getServerProps"),b=(0,i.l)(u,"unstable_getServerSideProps"),x=new s.PagesRouteModule({definition:{kind:a.x.PAGES,page:"/components/Icons",pathname:"/components/Icons",bundlePath:"",filename:""},components:{App:l.default,Document:n.default},userland:u})},5143:(e,t,r)=>{"use strict";r.r(t),r.d(t,{default:()=>a});var s=r(997);function a({Component:e,pageProps:t}){return s.jsx(e,{...t})}r(108)},29:(e,t,r)=>{"use strict";r.r(t),r.d(t,{default:()=>i});var s=r(997),a=r(6859);function i(){return(0,s.jsxs)(a.Html,{lang:"pt-br",children:[s.jsx("title",{children:"Calculadora de suplementa\xe7\xe3o"}),s.jsx(a.Head,{}),(0,s.jsxs)("body",{children:[s.jsx(a.Main,{}),s.jsx(a.NextScript,{})]})]})}},4113:(e,t,r)=>{"use strict";r.r(t),r.d(t,{default:()=>n});var s=r(997);/**
 * @license lucide-react v0.340.0 - ISC
 *
 * This source code is licensed under the ISC license.
 * See the LICENSE file in the root directory of this source tree.
 */let a=(0,r(4297).Z)("AlertTriangle",[["path",{d:"m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3Z",key:"c3ski4"}],["path",{d:"M12 9v4",key:"juzpu7"}],["path",{d:"M12 17h.01",key:"p32p05"}]]);var i=r(3756);let n={warning:s.jsx(a,{className:"text-yellow-400 size-12 pb-2 m-auto"}),success:s.jsx(i.Z,{className:"text-emerald-500 size-12 pb-2 m-auto"})}},108:()=>{},5244:(e,t)=>{"use strict";var r;Object.defineProperty(t,"x",{enumerable:!0,get:function(){return r}}),function(e){e.PAGES="PAGES",e.PAGES_API="PAGES_API",e.APP_PAGE="APP_PAGE",e.APP_ROUTE="APP_ROUTE"}(r||(r={}))},2785:e=>{"use strict";e.exports=require("next/dist/compiled/next-server/pages.runtime.prod.js")},6689:e=>{"use strict";e.exports=require("react")},997:e=>{"use strict";e.exports=require("react/jsx-runtime")},1017:e=>{"use strict";e.exports=require("path")}};var t=require("../../webpack-runtime.js");t.C(e);var r=e=>t(t.s=e),s=t.X(0,[859],()=>r(9472));module.exports=s})();