(()=>{var e={};e.id=301,e.ids=[301,888,660],e.modules={4297:(e,t,r)=>{"use strict";r.d(t,{Z:()=>i});var a=r(6689),s={xmlns:"http://www.w3.org/2000/svg",width:24,height:24,viewBox:"0 0 24 24",fill:"none",stroke:"currentColor",strokeWidth:2,strokeLinecap:"round",strokeLinejoin:"round"};/**
 * @license lucide-react v0.340.0 - ISC
 *
 * This source code is licensed under the ISC license.
 * See the LICENSE file in the root directory of this source tree.
 */let l=e=>e.replace(/([a-z0-9])([A-Z])/g,"$1-$2").toLowerCase().trim(),i=(e,t)=>{let r=(0,a.forwardRef)(({color:r="currentColor",size:i=24,strokeWidth:n=2,absoluteStrokeWidth:o,className:d="",children:u,...c},m)=>(0,a.createElement)("svg",{ref:m,...s,width:i,height:i,stroke:r,strokeWidth:o?24*Number(n)/Number(i):n,className:["lucide",`lucide-${l(e)}`,d].join(" "),...c},[...t.map(([e,t])=>(0,a.createElement)(e,t)),...Array.isArray(u)?u:[u]]));return r.displayName=`${e}`,r}},3756:(e,t,r)=>{"use strict";r.d(t,{Z:()=>a});/**
 * @license lucide-react v0.340.0 - ISC
 *
 * This source code is licensed under the ISC license.
 * See the LICENSE file in the root directory of this source tree.
 */let a=(0,r(4297).Z)("CheckCircle",[["path",{d:"M22 11.08V12a10 10 0 1 1-5.93-9.14",key:"g774vq"}],["path",{d:"m9 11 3 3L22 4",key:"1pflzl"}]])},1323:(e,t)=>{"use strict";Object.defineProperty(t,"l",{enumerable:!0,get:function(){return function e(t,r){return r in t?t[r]:"then"in t&&"function"==typeof t.then?t.then(t=>e(t,r)):"function"==typeof t&&"default"===r?t:void 0}}})},5874:(e,t,r)=>{"use strict";r.a(e,async(e,a)=>{try{r.r(t),r.d(t,{config:()=>f,default:()=>c,getServerSideProps:()=>p,getStaticPaths:()=>x,getStaticProps:()=>m,reportWebVitals:()=>h,routeModule:()=>j,unstable_getServerProps:()=>P,unstable_getServerSideProps:()=>y,unstable_getStaticParams:()=>g,unstable_getStaticPaths:()=>v,unstable_getStaticProps:()=>b});var s=r(7093),l=r(5244),i=r(1323),n=r(29),o=r(5143),d=r(5151),u=e([d]);d=(u.then?(await u)():u)[0];let c=(0,i.l)(d,"default"),m=(0,i.l)(d,"getStaticProps"),x=(0,i.l)(d,"getStaticPaths"),p=(0,i.l)(d,"getServerSideProps"),f=(0,i.l)(d,"config"),h=(0,i.l)(d,"reportWebVitals"),b=(0,i.l)(d,"unstable_getStaticProps"),v=(0,i.l)(d,"unstable_getStaticPaths"),g=(0,i.l)(d,"unstable_getStaticParams"),P=(0,i.l)(d,"unstable_getServerProps"),y=(0,i.l)(d,"unstable_getServerSideProps"),j=new s.PagesRouteModule({definition:{kind:l.x.PAGES,page:"/components/Modal",pathname:"/components/Modal",bundlePath:"",filename:""},components:{App:o.default,Document:n.default},userland:d});a()}catch(e){a(e)}})},5143:(e,t,r)=>{"use strict";r.r(t),r.d(t,{default:()=>s});var a=r(997);function s({Component:e,pageProps:t}){return a.jsx(e,{...t})}r(108)},29:(e,t,r)=>{"use strict";r.r(t),r.d(t,{default:()=>l});var a=r(997),s=r(6859);function l(){return(0,a.jsxs)(s.Html,{lang:"pt-br",children:[a.jsx("title",{children:"Calculadora de suplementa\xe7\xe3o"}),a.jsx(s.Head,{}),(0,a.jsxs)("body",{children:[a.jsx(s.Main,{}),a.jsx(s.NextScript,{})]})]})}},2764:(e,t,r)=>{"use strict";r.a(e,async(e,a)=>{try{r.r(t),r.d(t,{default:()=>o});var s=r(997),l=r(3756),i=r(5916),n=e([i]);i=(n.then?(await n)():n)[0];let d=(0,i.tv)({base:"rounded  text-sm font-medium text-zinc-900 bg-emerald-500 hover:bg-emerald-600",variants:{layout:{default:"h-9 px-4",sm:"h-8 px-3",xs:"h-6 px-2 text-xs",alert:"px-4 h-9 text-sm rounded font-medium text-zinc-900 bg-yellow-500 hover:bg-yellow-600",approved:"h-9 px-4 text-sm rounded font-medium text-zinc-900 bg-emerald-500 hover:bg-emerald-600"},success:{true:"bg-emerald-500 hover:bg-emerald-600"}},defaultVariants:{layout:"default",success:!1}});function o({success:e,layout:t,className:r,...a}){return(0,s.jsxs)("button",{type:"submit",className:d({layout:t,success:e,className:r}),...a,children:[a.children,e&&s.jsx(l.Z,{className:"w-4 h-4 inline ml-1"})]})}a()}catch(e){a(e)}})},4113:(e,t,r)=>{"use strict";r.r(t),r.d(t,{default:()=>i});var a=r(997);/**
 * @license lucide-react v0.340.0 - ISC
 *
 * This source code is licensed under the ISC license.
 * See the LICENSE file in the root directory of this source tree.
 */let s=(0,r(4297).Z)("AlertTriangle",[["path",{d:"m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3Z",key:"c3ski4"}],["path",{d:"M12 9v4",key:"juzpu7"}],["path",{d:"M12 17h.01",key:"p32p05"}]]);var l=r(3756);let i={warning:a.jsx(s,{className:"text-yellow-400 size-12 pb-2 m-auto"}),success:a.jsx(l.Z,{className:"text-emerald-500 size-12 pb-2 m-auto"})}},5151:(e,t,r)=>{"use strict";r.a(e,async(e,a)=>{try{r.r(t),r.d(t,{default:()=>o});var s=r(997),l=r(2764),i=r(4113),n=e([l]);function o({title:e,children:t,buttonText:r,icon:a,onClose:n,layout:o="default"}){let d={default:"relative w-auto my-6 mx-auto max-w-3xl",large:"relative my-6 mx-auto w-full max-w-6xl"},u=d[o]||d.default;return(0,s.jsxs)(s.Fragment,{children:[s.jsx("div",{className:"justify-center items-center flex overflow-x-hidden overflow-y-auto fixed inset-0 z-50 outline-none focus:outline-none",children:s.jsx("div",{className:`${u}`,children:(0,s.jsxs)("div",{className:"border-0 rounded-lg shadow-lg relative flex flex-col w-full bg-slate-800 outline-none focus:outline-none",children:[s.jsx("div",{className:" items-start justify-between p-3 border-b border-solid border-slate-500 rounded-t",children:(0,s.jsxs)("h3",{className:"text-3xl font-semibold text-center",children:[i.default[a],e]})}),s.jsx("div",{className:"relative flex-auto overflow-x-hidden overflow-y-auto p-6",children:t}),s.jsx("div",{className:"flex items-center justify-end p-6 border-t border-solid border-slate-500 rounded-b",children:s.jsx(l.default,{layout:"approved",onClick:()=>n(!1),children:r})})]})})}),s.jsx("div",{className:"opacity-25 fixed inset-0 z-40 bg-black"})]})}l=(n.then?(await n)():n)[0],a()}catch(e){a(e)}})},108:()=>{},5244:(e,t)=>{"use strict";var r;Object.defineProperty(t,"x",{enumerable:!0,get:function(){return r}}),function(e){e.PAGES="PAGES",e.PAGES_API="PAGES_API",e.APP_PAGE="APP_PAGE",e.APP_ROUTE="APP_ROUTE"}(r||(r={}))},2785:e=>{"use strict";e.exports=require("next/dist/compiled/next-server/pages.runtime.prod.js")},6689:e=>{"use strict";e.exports=require("react")},997:e=>{"use strict";e.exports=require("react/jsx-runtime")},5916:e=>{"use strict";e.exports=import("tailwind-variants")},1017:e=>{"use strict";e.exports=require("path")}};var t=require("../../webpack-runtime.js");t.C(e);var r=e=>t(t.s=e),a=t.X(0,[859],()=>r(5874));module.exports=a})();